// Market types

export const FETCH_MARKET_BEGIN = 'FETCH_MARKET_BEGIN'
export const FETCH_MARKET_SUCCESS = 'FETCH_MARKET_SUCCESS'
export const FETCH_MARKET_FAILURE = 'FETCH_MARKET_FAILURE'

// filterTop types

export const UPDATE_FILTER_BY = 'UPDATE_FILTER'
export const UPDATE_ASC = 'UPDATE_ASC'
