// Market types

export const FETCH_MARKET_BEGIN = 'FETCH_MARKET_BEGIN'
export const FETCH_MARKET_SUCCESS = 'FETCH_MARKET_SUCCESS'
export const FETCH_MARKET_FAILURE = 'FETCH_MARKET_FAILURE'

// topCoinsFilters types

export const UPDATE_FILTER_BY = 'UPDATE_FILTER'
export const UPDATE_ASC = 'UPDATE_ASC'
export const UPDATE_PAGINATION = 'UPDATE_PAGINATION'
export const UPDATE_DISPLAY = 'UPDATE_DISPLAY'
export const UPDATE_INPUT_FILTER = 'UPDATE_INPUT_FILTER'

// Asset types

export const FETCH_ASSET_BEGIN = 'FETCH_ASSET_BEGIN'
export const FETCH_ASSET_SUCCESS = 'FETCH_ASSET_SUCCESS'
export const FETCH_ASSET_FAILURE = 'FETCH_ASSET_FAILURE'
